# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'wyretrade' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    
    #Network
    pod 'Alamofire'
    
    pod 'NVActivityIndicatorView/Extended'
    pod 'SlideMenuControllerSwift', :git => 'https://github.com/AtomicSLLC/SlideMenuControllerSwift.git', :branch => 'swift5'
    pod 'UITextField+Shake'
    pod 'XLPagerTabStrip', '~> 9.0'

    
    pod 'AnyChartiOS', '~> 1.0.3'
    pod 'DropDown'
    pod 'DLRadioButton', '~> 1.4'
    pod 'RadioGroup'
    
    
    pod 'stellar-ios-mac-sdk', '~> 1.8.5'
    
    pod 'PhoneNumberKit'
    pod 'FlagPhoneNumber'
    pod 'SwiftyCodeView/RxSwift'
    
    pod 'Stripe'
    pod 'plaid-ios-sdk'
    pod 'PayPal-iOS-SDK'
    
    pod 'DeviceKit'
    
# Pods for MDC-Tutorial
  
  pod 'MaterialComponents/Cards'
  
  
  pod 'Firebase/Auth'
    
end
