# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'wyretrade' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    
    #Network
    pod 'Alamofire'
    
    pod 'NVActivityIndicatorView'
    pod 'SlideMenuControllerSwift', :git => 'https://github.com/AtomicSLLC/SlideMenuControllerSwift.git', :branch => 'swift5'
    pod 'UITextField+Shake'
    pod 'XLPagerTabStrip', '~> 9.0'
    pod 'PopupDialog', '~> 1.1'
    pod 'DLRadioButton', '~> 1.4'
    
    pod 'DeviceKit'
    
# Pods for MDC-Tutorial
  pod 'MaterialComponents/AppBar+Theming'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Collections'
  pod 'MaterialComponents/Cards'
  pod 'MaterialComponents/NavigationDrawer'
    
end
